pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('reviews/', include('reviews.urls')),
    path('socials/', include('allauth.urls')),
]

# media, static load for 'DEBUG = False'
# https://senticoding.tistory.com/82
urlpatterns += url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
urlpatterns += url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),


# only work in DEBUG mode
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    # 리뷰
    path("<int:product_pk>/", views.index, name="index"), # 리뷰 목록 리스트
    path("<int:product_pk>/create/", views.create, name="create"), # 상품 리뷰 작성
    path("<int:review_pk>/update/", views.update, name="update"), # 상품 리뷰 수정
    path("<int:review_pk>/delete/", views.delete, name="delete"), # 상품 리뷰 삭제
]

reviews/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill


class Review(models.Model):
    star_list = [
        ('⭐', '⭐'),
        ('⭐⭐', '⭐⭐'),
        ('⭐⭐⭐', '⭐⭐⭐'),
        ('⭐⭐⭐⭐', '⭐⭐⭐⭐'),
        ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐'),
    ]
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    star = models.CharField(max_length=5, choices=star_list)
    created_at = models.DateTimeField(auto_now_add = True)
    content = models.TextField()

reviews/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        exclude = (
            'user', 'like_users',
        )

reviews/views.py
from django.shortcuts import redirect, render
from products.models import Product
from .forms import ReviewForm
from .models import Review

def index(request, product_pk):
    product = Product.objects.get(id=product_pk)
    reviews = product.review.all()
    form = ReviewForm(instance=product)

    context = {
        'reviews': reviews,
        'product_pk': product_pk,
        'form' : form,
    }
    
    return render(request, 'reviews/index.html', context)


def create(request, product_pk):
    product = Product.objects.get(id=product_pk)

    if request.method == 'POST':
        form = ReviewForm(request.POST, request.FILES)

        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user

            if request.user not in product.review.all():
                review.save()
                product.review.add(review)
            # else:
                # 실패 alert 가 뜨게 만들어야함.

            return redirect('reviews:index', product_pk)

    else:
        form = ReviewForm()

    context = {
        'form': form
    }

    return render(request, 'reviews/forms.html', context)


def update(request, review_pk):
    review = Review.objects.get(id=review_pk)

    if request.method == 'POST':
        form = ReviewForm(request.POST, request.FILES, instance=review)

        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.save()

            return redirect('reviews:index', review.review_product.get().id)

    else:
        form = ReviewForm(instance=review)

    context = {
        'form': form
    }

    return render(request, 'reviews/forms.html', context)


def delete(request, review_pk):
    review = Review.objects.get(id=review_pk)
    product_pk = review.review_product.get().id
    review.delete()

    return redirect('reviews:index', product_pk)

reviews/templates/reviews/forms.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content_2 %}
{% if request.resolver_match.url_name == 'create' %}
<div class="container-fluid py-5 rounded" style="background-color: #E9EEF5;">
  <div class="col-md-6 m-auto text-center">
      <h1 class="h1">리뷰 작성</h1>
  </div>
</div>
{% else %}
<div class="container-fluid py-5 rounded" style="background-color: #E9EEF5;">
  <div class="col-md-6 m-auto text-center">
      <h1 class="h1">리뷰 수정</h1>
  </div>
</div>
{% endif %}
<div class="d-flex justify-content-center align-items-center m-auto mt-5">
  <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% bootstrap_button content="ok" button_type="submit" button_class="btn-danger" %}
  </form>
</div>

{% endblock content_2 %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <h1 class="text-center my-4" style="color: #212934;">리뷰 목록</h1>

  
    {% for review in reviews %}
      <div class="bg-light rounded" style="box-shadow: 4px 4px 4px rgb(0, 0, 0, 0.2); width: 80%; margin: auto;">
        <div class="d-flex justify-content-between align-items-center">
          <div class="d-flex align-items-center">
            <i class="bi bi-person-circle fs-1 m-2 me-3"></i>
            <div>
              <div>
                <p class="fs-6 mb-0">{{ review.user }}</p>
                <p class="mb-0 text-muted d-none d-lg-block" style="font-size: 12px;"> {{ review.created_at }}</p>
                {% if request.user == review.user %}    
                  <div class="d-flex">
                    <a class="me-1" style="color: orange; text-decoration: none; font-size: 10px;" href="{% url 'reviews:update' review.id %}" >
                      수정하기<i class="bi bi-check2-circle"></i>
                    </a>
                    <a style="color: #F96666; text-decoration: none; font-size: 10px;" href="{% url 'reviews:delete' review.id %}">
                      삭제하기 <i class="bi bi-x-circle"></i>
                    </a>
                  </div>
                {% endif %}
              </div>
            </div>
          </div>
          <p  class="mb-0 me-5" style="font-size: 14px;"> {{ review.star }}</p>
        </div> 
        <hr class="m-0">
        <p class="m-4 pb-4"> {{ review.content }}</p>
      </div>
    {% endfor %}
      


<div class="d-flex justify-content-end">
    <a class="btn btn-dark" href="{% url 'reviews:create' product_pk %}">
      작성하기
    </a>
</div>  

  


{% endblock content %}