accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('register_seller/<int:user_pk>', views.register_seller, name='register_seller'),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('reviews/', include('reviews.urls')),
    path('socials/', include('allauth.urls')),
]

# media, static load for 'DEBUG = False'
# https://senticoding.tistory.com/82
urlpatterns += url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
urlpatterns += url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),


# only work in DEBUG mode
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    # 상품
    path("", views.index, name="index"), # 상점이 있는 메인 화면(상점 리스트)
    path("create/", views.create, name="create"), # 상품 글 작성
    path("<int:product_pk>/", views.detail, name="detail"), # 상품 조회 페이지
    path("<int:product_pk>/update/", views.update, name="update"), # 상품 글 수정
    path("<int:product_pk>/delete/", views.delete, name="delete"), # 상품 글 삭제
    path("<int:product_pk>/add_cart/", views.add_cart, name="add_cart"), # 장바구니 상품 담기
    path("show_cart/<int:user_pk>/", views.show_cart, name="show_cart"), # 장바구니 조회
    path("delete_cart/<int:product_pk>", views.delete_cart, name="delete_cart"), # 장바구니 상품 삭제
]

templates/base.html
<!DOCTYPE html>
{% load django_bootstrap5 %}
{% load static %}
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SPJT-01</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <!-- Google Font Nanum Gothic -->
    <link rel="preconnect" href="https://fonts.googleapis.com/">
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@700&display=swap" rel="stylesheet">

    <style>
      body {
        font-family: 'Nanum Gothic', sans-serif;
      }
    </style>
      
</head>
<body class="d-flex flex-column min-vh-100">
  <nav class="navbar navbar-expand-lg navbar-light d-none d-lg-block" id="templatemo_nav_top" style="background-color: #212934;">
    <div class="container text-light">
      <div class="w-100 d-flex justify-content-between">
        <div>
          <i class="bi bi-envelope mx-2" style="font-size:12px;"></i>
          <a class="navbar-sm-brand text-light text-decoration-none" href="" style="font-size:12px;">fourlee@hphk.com</a>
          <i class="bi bi-telephone-fill mx-2" style="font-size:12px;"></i>
          <a class="navbar-sm-brand text-light text-decoration-none" href="" style="font-size:12px;">444-2222</a>
        </div>
        <div>
          <a class="text-light" href="https://github.com/qlghwp123" target="_blank" rel="sponsored"><i class="bi bi-github me-2" style="font-size:15px;"></i></a>
          <a class="text-light" href="https://github.com/rrwe23" target="_blank" rel="sponsored"><i class="bi bi-github me-2" style="font-size:15px;"></i></a>
          <a class="text-light" href="https://github.com/leejongeun2" target="_blank" rel="sponsored"><i class="bi bi-github" style="font-size:15px;"></i></a>
        </div>
      </div>
    </div>
  </nav>
  <nav class="navbar navbar-expand-lg navbar-light shadow">
    <div class="container d-flex justify-content-between align-items-center">
      <a class="navbar-brand logo h1 align-self-center fs-1" style="color: #212934" href="{% url 'products:index' %}">
            FourLee
      </a>

      <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#templatemo_main_nav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>

      <div class="align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between" id="templatemo_main_nav">
        <div class="flex-fill">
          <ul class="nav navbar-nav mx-lg-auto">
            {% if request.user.is_authenticated %}
              {% if request.user.is_seller %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:create' %}">상품 등록</a>
                </li>
              {% endif %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
              </li>
              {% if not request.user.is_seller %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:register_seller' request.user.id %}">판매자 등록</a>
              </li>
              {% endif %}
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
              </li>
            {% endif %}
            
          </ul>
        </div>
        {% if request.user.is_authenticated %}
        <div class="navbar align-self-center d-flex">
          <a class="nav-icon position-relative text-decoration-none mx-4" href="{% url 'products:show_cart' request.user.id %}">
            <i class="bi bi-cart-x-fill text-dark fs-3"></i>
          </a>
          <a class="nav-icon position-relative text-decoration-none" href="{% url 'accounts:profile' %}">
            <i class="bi bi-person-circle text-dark fs-3"></i>
          </a>
        </div>
        {% endif %}
      </div>
    </div>
  </nav>

  <div>
    {% block content_2 %}{% endblock content_2 %}
  </div>

 
  <div class="container mb-5">
    {% block content %}{% endblock content %}
  </div>
  <footer class="mt-auto" style="background-color: #212934;">
    <div class="w-100 py-3">
        <div class="container">
            <div class="row pt-2">
                <div class="col-12">
                    <p class="text-center text-light" style="font-size:12px;">
                        Copyright &copy; 2022 이동근 이주현 이종은
                    </p>
                </div>
            </div>
        </div>
    </div>
  </footer>

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>

</html>