pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('reviews/', include('reviews.urls')),
    path('socials/', include('allauth.urls')),
]

# media, static load for 'DEBUG = False'
# https://senticoding.tistory.com/82
urlpatterns += url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
urlpatterns += url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),


# only work in DEBUG mode
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    # 상품
    path("", views.index, name="index"), # 상점이 있는 메인 화면(상점 리스트)
    path("create/", views.create, name="create"), # 상품 글 작성
    path("<int:product_pk>/", views.detail, name="detail"), # 상품 조회 페이지
    path("<int:product_pk>/update/", views.update, name="update"), # 상품 글 수정
    path("<int:product_pk>/delete/", views.delete, name="delete"), # 상품 글 삭제
    path("<int:product_pk>/add_cart/", views.add_cart, name="add_cart"), # 장바구니 상품 담기
    path("show_cart/<int:user_pk>/", views.show_cart, name="show_cart"), # 장바구니 조회
    path("delete_cart/<int:product_pk>", views.delete_cart, name="delete_cart"), # 장바구니 상품 삭제
]

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    # 리뷰
    path("<int:product_pk>/", views.index, name="index"), # 리뷰 목록 리스트
    path("<int:product_pk>/create/", views.create, name="create"), # 상품 리뷰 작성
    path("<int:review_pk>/update/", views.update, name="update"), # 상품 리뷰 수정
    path("<int:review_pk>/delete/", views.delete, name="delete"), # 상품 리뷰 삭제
]

products/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from reviews.models import Review



class Product(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    price = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add = True)
    image = ProcessedImageField(upload_to='images/', blank=True,
                                    processors=[ResizeToFill(640,480)],
                                    format='JPEG',
                                    options={'quality':90})
    content = models.TextField()
    cart = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name = 'cart_product')
    review = models.ManyToManyField(Review, related_name = 'review_product')


                    










products/forms.py
from dataclasses import field
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = (
            "user",
            "cart",
            "review",
        )
        # field = ['name', 'price', 'thumbnail', 'image', 'content']

products/views.py
from django.shortcuts import render, redirect
from .models import Product
from django.contrib.auth import get_user_model
from .forms import ProductForm
import random

def index(request):
    products = Product.objects.all()

    context = {
        "products": products,
    }

    return render(request, "products/index.html", context)
    

def create(request):
    if request.method == "POST":
        product_form = ProductForm(request.POST, request.FILES)

        if product_form.is_valid():
            product = product_form.save(commit=False)
            product.user = request.user
            product.save()

            return redirect('products:index')

    else:
        product_form = ProductForm()

    context = {
        "product_form": product_form
    }

    return render(request, "products/forms.html", context)


def detail(request, product_pk):
    product = Product.objects.get(id=product_pk)

    context = {
        "product":product
    }

    return render(request, "products/detail.html", context)
    

def update(request, product_pk):
    product = Product.objects.get(id=product_pk)

    if request.method == "POST":
        product_form = ProductForm(request.POST, request.FILES, instance=product)

        if product_form.is_valid():
            product_form.save()

            return redirect("products:detail", product_pk)
    else:
        product_form = ProductForm(instance=product)

    context = {
        "product_form": product_form
    }

    return render(request, "products/forms.html", context)

def delete(request, product_pk):
    product = Product.objects.get(id=product_pk)
    product.delete()

    return redirect("products:index")


def add_cart(request, product_pk):
    product = Product.objects.get(id=product_pk)

    if request.user in product.cart.all():
        product.cart.remove(request.user)
    else:
        product.cart.add(request.user)
        
    return redirect('products:detail', product_pk)


def show_cart(request, user_pk):
    cart = get_user_model().objects.get(id=user_pk).cart_product.all()
    
    context = {
        'cart': cart
    }

    return render(request, 'products/wishlist.html', context)


def delete_cart(request, product_pk):
    Product.objects.get(id=product_pk).cart.remove(request.user)

    return redirect('products:show_cart', request.user.pk)

products/templates/products/detail.html
{% extends 'base.html' %}

{% load humanize %}

{% block content %}
<div>
    <div class="d-flex flex-column align-items-center mt-5">
        <div>
            <div class="d-flex">
                <div style="width:50%;">
                <hr class="border-5">
                <h4>{{ product.name }}</h4>
                <div class=" dd d-flex justify-content-between">
                    <h5>\
                    {{ product.price | intcomma }}</h5>
                    <a href="{% url 'products:add_cart' product.pk %}">
                    {% if request.user in product.cart.all %}
                        <i class="bi bi-cart-check-fill fs-3 text-dark"></i>
                    {% else %}
                        <i class="bi bi-cart-check fs-3 text-dark"></i>
                    {% endif %}
                    </a>
                </div>
                <hr class="border-5 ">
                <div>
                    <p class="fs-5">Delivery Info</p>
    
                    <div class="d-flex justify-content-between">
                    <p style="font-size:0.8em;">출고 정보</p>
                    <p style="font-size:0.8em;">
                        결제 3일 이내 출고</p>
                    </div>
                    <div class="d-flex justify-content-between mx-1">
                    <p style="font-size:0.8em;">배송비</p>
                    <p class="mx-5" style="font-size:0.8em;">
                        무료배송
                    </p>
                    </div>
    
                    <hr class="border-5 ">
                    <div class="d-flex justify-content-center">
    
                    <a href="{% url 'products:add_cart' product.pk %}" class="btn btn-dark btn-lg btn-block">장바구니 담기</a>
                    </div>
                    <hr class="border-5 ">
                    <div class="d-flex justify-content-between">
                    <p style="font-size:0.8em;">판매자</p>
    
                    <p style="font-size:0.8em;">
                        {{ product.user }}</p>
                    </div>
                    {% if request.user == product.user %}
                    <div class="d-flex justify-content-center ">
                        <a href="{% url 'products:update' product.pk %}" class="btn btn-outline-dark mx-1">수정하기</a>
                        <a href="{% url 'products:delete' product.pk %}" class="btn btn-outline-dark mx-1">삭제하기</a>
                    </div>
                    {% endif %}
                </div>
                </div>
    
                <div class="d-flex flex-column justify-content-center mx-5">
                    {% if product.image %}
                        <img class="rounded mx-5" style="box-shadow: 4px 4px 4px rgb(0, 0, 0, 0.2); width: 80%; height: 100%;" src="{{ product.image.url }}" alt="123">
                    {% else %}
                        <img class="rounded mx-5" style="box-shadow: 4px 4px 4px rgb(0, 0, 0, 0.2); width: 80%; height: 100%;" src="https://dummyimage.com/640x480/000/454545" alt="123">
                    {% endif %}
                </div>
            </div>
            <div class="my-5">
                <p class="text-center">{{ product.content | linebreaks }}</p>
            </div>
            <div class="text-center">
                <a href="{% url 'reviews:index' product.pk %}" class="btn btn-outline-dark"  style="width: 100%;">리뷰</a>
            </div>
        </div>
        
    </div>



    <div>
      <div class="mt-5 d-flex justify-content-center">
        <p style="font-size:0.5em;">등록날짜 :
          {{ product.created_at }}</p>

      </div>
    </div>
   
</div>
  
{% endblock content %}

products/templates/products/forms.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content_2 %}
{% if request.resolver_match.url_name == 'create' %}
<div class="container-fluid py-5 rounded" style="background-color: #E9EEF5;">
    <div class="col-md-6 m-auto text-center">
        <h1 class="h1">상품 등록</h1>
    </div>
</div>
{% else %}
<div class="container-fluid py-5 rounded" style="background-color: #E9EEF5;">
    <div class="col-md-6 m-auto text-center">
        <h1 class="h1">상품 수정</h1>
    </div>
</div>
{% endif %}
<div class="d-flex justify-content-center align-items-center m-auto mt-5">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form product_form %}
        {% bootstrap_button content="ok" button_type="submit" button_class="btn-danger" %}
    </form>
</div>





{% endblock content_2 %}

products/templates/products/index.html
{% extends 'base.html' %}

{% load humanize %}

{% block content %}

  <div class="row mb-3">
    <div id="carousel" class="carousel slide" data-bs-ride="carousel" data-bs-animation="1000" style="object-fit: cover;min-height: 200px;">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="https://maison-mined.com/web/upload/q/opengraph.jpg" class="d-block w-100" alt="Error" style="height: 650px;">
        </div>
        <div class="carousel-item">
          <img src="http://comino7981.cafe24.com/wp-content/uploads/2018/07/maxresdefault-3.jpg" class="d-block w-100" alt="Error" style="height: 650px;">
        </div>
        <div class="carousel-item">
          <img src="http://m.lfcorp.com/upload/editor/4b993b106f7c430182e780f18f3a645f.jpg" class="d-block w-100" alt="Error" style="height: 650px;">
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>

  <div class="row row-cols-3 row-cols-md-3 g-4">
    {% for product in products %}
      <div class="col">
        <div class="card h-100" style="box-shadow: 4px 4px 4px rgb(0, 0, 0, 0.2);">
          <a href=" {% url 'products:detail' product.id %}">
            {% if product.image %}
              <img src="{{ product.image.url }}" class="card-img-top" alt="...">
            {% else %}
              <img src="https://dummyimage.com/640x480/000/454545" class="card-img-top" alt="...">
            {% endif %}
          </a>
          <div class="card-body">
            <h5 class="card-title">{{ product.name }}</h5>
            <p class="card-text">{{ product.star }}</p>
            <p class="card-text"> \ {{ product.price | intcomma }}</p>
            <p class="text-muted">Reviews ({{ product.review.count }})</p>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

{% endblock content %}

products/templates/products/main.html
{% extends 'base.html' %}

{% block content %}

<h1>main</h1>

{% for product in products %}

<div style="width: 480px; height: 320px;">
    <a href="{% url 'products:detail' product.pk %}">
        <img src="{{ product.image.url }}" style="width: 480px; height: 320px;">
    </a>
    <p>{{ product.name }}</p>
    <hr>
    <p>{{ product.price }}원</p>
</div>

{% endfor %}

{% endblock content %}

products/templates/products/wishlist.html
{% extends 'base.html' %}

{% block content_2 %}
<div class="container-fluid py-5 rounded" style="background-color: #E9EEF5;">
    <div>
        <h1 class="text-center"><i class="bi bi-cart4 mx-1"></i>장바구니</h1>
    </div>
</div>


{% for product in  cart %}
<div class="d-flex justify-content-between align-items-center rounded border my-3 bg-light" style="width: 70%; margin: auto;">
    <div class="d-flex align-items-center m-3">
        <img class="rounded" src="{{ product.image.url }}" alt="123" style="width: 150px; height:150px;">
        <div class="ms-5">
            <p>{{ product.name }}</p>
            <p>{{ product.price }}원</p>
        </div>
    </div>
    <a href="{% url 'products:delete_cart' product.pk %}"><i class="bi bi-trash text-danger fs-4 m-3"></i></a>
</div>


{% endfor %}

{% endblock content_2 %}